services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: